FROM mongo:6.0.24@sha256:d7550694c4bd01021f0abda310e6fd353445ad68f9ccd40a1ecf034c150cc6a8

COPY ./dump /docker-entrypoint-initdb.d/dump
COPY ./init.sh /docker-entrypoint-initdb.d/init.sh

RUN chmod +x /docker-entrypoint-initdb.d/init.sh
