FROM cypress/browsers:node-22.16.0-chrome-137.0.7151.119-1-ff-139.0.4-edge-137.0.3296.62-1@sha256:b290f975e7fc7ee22959b48f12e64c67793d9a9ad78cfbf97e59886f4fc58ee0

# Create non-root user early to avoid running as root
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID cypress && \
    useradd -m -u $UID -g cypress cypress

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci && npx cypress install

COPY . .

# Set /app ownership to the non-root user
RUN chown -R cypress:cypress /app
USER cypress
