FROM node:16-slim@sha256:3ebf2875c188d22939c6ab080cfb1a4a6248cc86bae600ea8e2326aa03acdb8f

WORKDIR /app
COPY package.json /app
COPY package-lock.json /app
RUN npm install 
COPY . .
EXPOSE 17000
CMD ["npm", "start"]
