FROM node:22-slim@sha256:048ed02c5fd52e86fda6fbd2f6a76cf0d4492fd6c6fee9e2c463ed5108da0e34

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm install

COPY . .
EXPOSE 17000
CMD ["npm", "start"]
