FROM node:22-slim@sha256:b04ce4ae4e95b522112c2e5c52f781471a5cbc3b594527bcddedee9bc48c03a0

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm install

COPY . .

USER node

EXPOSE 17000
CMD ["npm", "start"]
