version: "3.9"
services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    ports:
      - "17000:17000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"
      MONGODB_NAME: "ani"
      NODE_ENV: "development"
      PORT: "17000"
      CORS_WHITELIST: "http://localhost:3000"

  mongodb:
    build:
      context: ../db/mongo
      dockerfile: Dockerfile.dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ani
    restart: always

  nginx:
    build:
      context: ..
      dockerfile: ./nginx/Dockerfile.dev
    depends_on:
      - backend
    ports:
      - "3000:3000"
