#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- Build Docker Images --------------------"

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <DOCKER_USER> <VERSION>"
  exit 1
fi

DOCKER_USER=$1
VERSION=$2

auto/build-frontend-dev
auto/build-frontend-artifacts

docker build -f ./backend/Dockerfile.dev -t $DOCKER_USER/forum-backend:$VERSION .
docker build -f ./nginx/Dockerfile.dev -t $DOCKER_USER/forum-nginx:$VERSION .
