#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

VERSION=$1

git config user.name "${GITHUB_ACTOR}"
git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
git tag "$VERSION"
git push origin "$VERSION"
