#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

pr_body="$1"

labels=$(echo "$pr_body" | grep -iE '^\s*-\s*\[x\]\s*/kind ' | sed -E 's/.*\/kind ([^ ]+).*/kind\/\1/')

if [[ -n "$labels" ]]; then
  echo "labels=$(echo "$labels" | paste -sd "," -)" >> "$GITHUB_OUTPUT"
else
  echo "labels=" >> "$GITHUB_OUTPUT"
fi
