#!/bin/bash
cd $(dirname ..)

echo "-------------------- Build Frontend --------------------"
docker build -t frontend-dev -f frontend/Dockerfile.dev ./frontend
docker run -p 3000:3000 --rm -v "$(pwd)/frontend/build:/app/build" frontend-dev serve -s build
