#!/bin/bash
cd $(dirname ..)

echo "-------------------- Build Frontend --------------------"
docker build -t frontend-dev -f frontend/Dockerfile.dev ./frontend
docker run --rm -v "$(pwd)/frontend/build:/app/build" frontend-dev npm run build
