#!/bin/bash
cd $(dirname ..)

docker compose up -d
sleep 20

echo "health checking..."
if curl -s http://localhost:3000/ | grep -q "<title>Ani Ani</title>"; then
    echo "✅ frontend health check pass"
else
    echo "❌ frontend health check failed"
    echo "docker compose ps:"
    docker compose ps
fi

if curl -s http://localhost:3000/healthcheck | grep -q "Health Check Pass! The frontend is connected to backend!"; then
    echo "✅ backend health check pass"
else
    echo "❌ backend health check failed"
    echo "docker compose ps:"
    docker compose ps
fi

docker compose down
