#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- Launching AniAni --------------------"
auto/build-frontend-dev
auto/build-frontend-artifacts
auto/run-docker-compose
