#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- Starting Docker Compose --------------------"

ENV=${ENV}

if [ "${ENV}" == "local"  ]; then
  echo "Using local environment configuration"
  docker_compose_params="deploy/docker-compose.local.yml"
elif [ "${ENV}" == "test" ]; then
  echo "Using test environment configuration"
else
  echo "ENV is not set or invalid, please set ENV to 'test', or 'test'."
  echo "Exiting..."
  exit 1
fi

if [ "${ENV}" == "local"  ]; then
  docker compose -f docker-compose.temp.yml -f "${docker_compose_params}" down -v
fi

docker compose -f docker-compose.temp.yml -f "${docker_compose_params}" up -d

sleep 20
