#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."

auto/run-docker-compose

echo "-------------------- Run E2E Tests --------------------"
cd frontend
docker run --network=host frontend-dev npx cypress run
