#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- 🍱 Preparing Environment for E2E Tests --------------------"
if [ "${ENV}" != "test" ]; then
  auto/launch-app
fi

echo "-------------------- 🧪 Running E2E Tests --------------------"
cd frontend
docker rm -f cypress-e2e || true
docker run --rm --name cypress-e2e --network=host \
    -v "$(pwd)/cypress/screenshots:/app/cypress/screenshots" \
    frontend-dev npx cypress run
