#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- Starting Docker Compose --------------------"

#if [[ $# -ne 1 ]]; then
#  echo "Usage: $0 <ENV>"
#  exit 1
#fi
#
#ENV=$1
ENV=${ENV}

if [ "${ENV}" == "test"  ]; then
  echo "Using test environment configuration"
  docker_compose_template="deploy/docker-compose.test.yml"
elif [ "${ENV}" == "staging" ]; then
  echo "Using staging environment configuration"
elif [ "${ENV}" == "prod" ]; then
  echo "Using prod environment configuration"
else
  echo "ENV is not set or invalid, exiting..."
  exit 1
fi

if [ "${ENV}" == "test"  ]; then
  docker compose -f deploy/docker-compose.yml "${docker_compose_template}" down -v
fi

docker compose -f deploy/docker-compose.yml "${docker_compose_template}" up -d

sleep 20
