#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")/.."

echo "-------------------- Starting Docker Compose for Development Environment  --------------------"
auto/build-frontend-dev
auto/build-frontend-artifacts
auto/run-docker-compose
