FROM nginx:1.29.0@sha256:93230cd54060f497430c7a120e2347894846a81b6a5dd2110f7362c5423b4abc

RUN rm /etc/nginx/conf.d/default.conf

COPY ./frontend/build /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

