FROM nginx:1.29.0@sha256:dc53c8f25a10f9109190ed5b59bda2d707a3bde0e45857ce9e1efaa32ff9cbc1

RUN rm /etc/nginx/conf.d/default.conf

COPY ../frontend/build /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

